spring:
  application:
    name: service-one
eureka:
  client:
    serviceUrl:
      defaultZone: http://172.17.0.2:8088/eureka/  
  instance:
    hostname: localhost
    instance-id: http://localhost:8081
    prefer-ip-address: true
server:
  port: 8081
